_BASE_: "../Base-CondInst.yaml"
DATALOADER:
  IS_STACK: True
  FILTER_EMPTY_ANNOTATIONS: False
  ASPECT_RATIO_GROUPING: False
INPUT:
  MIN_SIZE_TRAIN: (480,)
  MIN_SIZE_TEST: 480
  STACK_SIZE: 11
  EXTENSION: ".png"
  SLICE_SEPARATOR: "F"
  HFLIP_TRAIN: False
  CROP:
    ENABLED: False
  IS_ROTATE: False
MODEL:
  META_ARCHITECTURE: "CondInst_Z"
  WEIGHTS: ""
  BACKBONE:
    FREEZE_AT: 0
  USE_AMP: True
  PIXEL_MEAN: [87.779, 100.134, 101.969]
  PIXEL_STD: [16.368, 13.607, 13.170]
SOLVER:
  IMS_PER_BATCH: 16
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 500
  BASE_LR: 0.001
  WARMUP_ITERS: 2000
  STEPS: (7000,)
TEST:
  AUG:
    ENABLED: False
