_BASE_: "../Base-CondInst.yaml"
INPUT:
  IS_STACK: True
  MIN_SIZE_TRAIN: (480,)
  MIN_SIZE_TEST: 480
  STACK_SIZE: 11
  EXTENSION: ".png"
  SLICE_SEPARATOR: "F"
  HFLIP_TRAIN: False
  CROP:
    ENABLED: False
  IS_ROTATE: False
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  ASPECT_RATIO_GROUPING: False
MODEL:
  META_ARCHITECTURE: "CondInst_Z"
  WEIGHTS: ""
  BACKBONE:
    FREEZE_AT: 0
  FCOS:
    NMS_TH: 0.7
  CONDINST:
    MASK_NMS_TH: 0.4
  USE_AMP: True
  PIXEL_MEAN: [87.779, 100.134, 101.969]
  PIXEL_STD: [16.368, 13.607, 13.170]
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  MAX_ITER: 20000
  STEPS: (15000,)
  WARMUP_ITERS: 2000
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 1000
  AUG:
    ENABLED: False
  IOU_METRIC_TH: 0.6
