_BASE_: "Base-CondInstZ.yaml"
MODEL:
  BACKBONE:
    DIM: 3
  RESNETS:
    DEPTH: 11
    NORM: "BN3d"
    STEM_OUT_CHANNELS: 16
    RES2_OUT_CHANNELS: 16
  FPN:
    OUT_CHANNELS: 16
  FCOS:
    SIZES_OF_INTEREST: [32, 64, 128, 256]
    NUM_CLS_CONVS: 1
    NUM_BOX_CONVS: 1
    NORM: "BN"
  CONDINST:
    MASK_BRANCH:
      NUM_CONVS: 1
      CHANNELS: 16
      OUT_CHANNELS: 8
    MASK_HEAD:
      NUM_LAYERS: 2
      CHANNELS: 4
  SEPARATOR:
    NAME: "From3dTo2d"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.1
  MAX_ITER: 40000
  STEPS: (20000, 35000)
  WARMUP_ITERS: 2000
  CHECKPOINT_PERIOD: 1000
  WEIGHT_DECAY: 0.001
  WEIGHT_DECAY_BIAS: 0.001
  MOMENTUM: 0.75
  DAMPENING: 0.75
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/CondInstZ_R_11_3d"
