_BASE_: "Base-CondInst.yaml"
INPUT:
  IS_STACK: False
  MIN_SIZE_TRAIN: (480,)
  MIN_SIZE_TEST: 480
  HFLIP_TRAIN: False
  CROP:
    ENABLED: False
  IS_ROTATE: False
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  ASPECT_RATIO_GROUPING: False
MODEL:
  WEIGHTS: ""
  BACKBONE:
    FREEZE_AT: 0
    DIM: 2
  RESNETS:
    DEPTH: 11
    NORM: "BN"
    STEM_OUT_CHANNELS: 16
    RES2_OUT_CHANNELS: 16
  FPN:
    OUT_CHANNELS: 16
  FCOS:
    SIZES_OF_INTEREST: [32, 64, 128, 256]
    NUM_CLS_CONVS: 1
    NUM_BOX_CONVS: 1
    NORM: "BN"
    NMS_TH: 0.7
  CONDINST:
    MASK_BRANCH:
      NUM_CONVS: 1
      CHANNELS: 16
      OUT_CHANNELS: 8
    MASK_HEAD:
      NUM_LAYERS: 2
      CHANNELS: 4
    MASK_NMS_TH: 0.4
  USE_AMP: True
  PIXEL_MEAN: [87.779, 100.134, 101.969]
  PIXEL_STD: [16.368, 13.607, 13.170]
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  MAX_ITER: 100000
  STEPS: (70000,)
  WARMUP_ITERS: 20000
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
  AUG:
    ENABLED: False
  IOU_METRIC_TH: 0.6
OUTPUT_DIR: "output/CondInst_R_11"
