_BASE_: "Base-CondInst.yaml"
INPUT:
  IS_STACK: False
  MIN_SIZE_TRAIN: (480,)
  MIN_SIZE_TEST: 480
  HFLIP_TRAIN: False
  CROP:
    ENABLED: False
  IS_ROTATE: False
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  ASPECT_RATIO_GROUPING: False
MODEL:
  WEIGHTS: ""
  BACKBONE:
    FREEZE_AT: 0
    DIM: 2
  RESNETS:
    DEPTH: 11
    NORM: "BN2d"
  USE_AMP: True
  PIXEL_MEAN: [87.779, 100.134, 101.969]
  PIXEL_STD: [16.368, 13.607, 13.170]
SOLVER:
  IMS_PER_BATCH: 16
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 5000
  BASE_LR: 0.001
  WARMUP_ITERS: 20000
  STEPS: (70000,)
TEST:
  AUG:
    ENABLED: False
OUTPUT_DIR: "output/CondInst_R_10"
